[package]
name = "gltf"
version = "0.16.0"
authors = ["David Harvey-Macaulay <alteous@outlook.com>"]
description = "glTF 2.0 loader"
documentation = "https://docs.rs/gltf"
repository = "https://github.com/gltf-rs/gltf"
homepage = "https://github.com/gltf-rs/gltf"
readme = "README.md"
keywords = ["glTF", "3D", "asset", "model", "scene"]
license = "MIT/Apache-2.0"
include = ["**/*.rs", "Cargo.toml"]
edition = "2018"

[badges]
travis-ci = { repository = "gltf-rs/gltf" }

[workspace]
members = ["gltf-derive", "gltf-json"]

[dev-dependencies]
approx = "0.3"

[dependencies]
base64 = { optional = true, version = "0.12" }
byteorder = "1.3"
gltf-json = { path = "gltf-json", version = "0.16.0" }
lazy_static = "1"

[dependencies.image]
default-features = false
features = ["jpeg", "png"]
optional = true
version = "0.23"

[features]
default = ["import", "utils", "names"]
extras = ["gltf-json/extras"]
names = ["gltf-json/names"]
preserve_order = ["gltf-json/preserve_order"]
utils = []
import = ["base64", "image"]
KHR_lights_punctual = ["gltf-json/KHR_lights_punctual"]
KHR_materials_pbrSpecularGlossiness = ["gltf-json/KHR_materials_pbrSpecularGlossiness"]
KHR_materials_unlit = ["gltf-json/KHR_materials_unlit"]
KHR_texture_transform = ["gltf-json/KHR_texture_transform"]
KHR_materials_transmission = ["gltf-json/KHR_materials_transmission"]
KHR_materials_ior = ["gltf-json/KHR_materials_ior"]
image_jpeg_rayon = ["image/jpeg_rayon"]
guess_mime_type = []

[[example]]
name = "gltf-display"
path = "examples/display/main.rs"

[[example]]
name = "gltf-export"
path = "examples/export/main.rs"

[[example]]
name = "gltf-roundtrip"
path = "examples/roundtrip/main.rs"

[[example]]
name = "gltf-tree"
path = "examples/tree/main.rs"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
